spring:
  application:
    name: schedule_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socks?useSSL=false&characterEncoding=UTF-8&?useUnicode=true
    username: root
    password: root
server:
  port: 8080
